// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbgiwswtpywiiqiakhnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZ2l3c3d0cHl3aWlxaWFraG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDcxMzgsImV4cCI6MjA2MDA4MzEzOH0.dZh5YRhF6a-qsxfp5o8ZKTb4ksBEn6jdThbuTswydxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);